### ISSUE TITLE
Manuscript title

### ISSUE THREAD

**Issue by mvuorre** [mvuorre/rparp#2]
I think we don't need vertical in the title because the proposal--in my mind--is a bit broader. How about

### Enabling fully reproducible research projects with R

This one is short and snappy and gets to the point pretty well. Maybe instead of "R" it could be "R packages". Or some variation of this, such as "R packages are a one-platform solution to reproducible research projects". @CrumpLab ?

**Comment by CrumpLab** [comment]
How about one of these?

- vertical: A tool for adopting R standards to create, curate, and communicate reproducible research projects
- vertical: Adopting R standards to create, curate, and communicate reproducible research projects
- vertical: Adopting R standards for creating, curating, and communicating reproducible research projects

**Comment by CrumpLab** [comment]
I'm going to close this issue given it seems we've settled on the new title!
