### ISSUE TITLE
Move the manuscript to CrumpLab/vertical/vignettes

### ISSUE THREAD

**Issue by mvuorre** [mvuorre/rparp#6]
It seems that this manuscript could be part of the vertical project.  What do you think @CrumpLab ? We can just move the Rmd to vertical/vignettes to include it on the vertical website directly.

**Comment by CrumpLab** [comment]
I'm fine with doing this, but a couple things. Would you still maintain this repository? If not, you then  we should take out the reference to this website in the paper. 

If we put it in vignettes it should also render as an html. We could like to the html and pdf versions? Let me try this out in vertical dev and see what happens.

**Comment by mvuorre** [comment]
We can take out all mentions of the "rparp" website from the paper, they are unnecessary anyway.

The manuscript doesn't need to render as HTML, we can just put in the pkgdown as_is tag, and the link will take to the PDF.

Almost done with "final" edits to the MS!

**Comment by mvuorre** [comment]
We need to add

```
pkgdown:
  as_is: true
  extension: pdf
```

to the manuscript yml. 

<https://github.com/r-lib/pkgdown/blob/master/vignettes/test/pdf.Rmd>

**Comment by CrumpLab** [comment]
I was just trying this. I added the above and get the following error on build site:

```
pkgdown::build_site()
── Installing package into temporary library ───────────────────────────────────────────────────────
══ Building pkgdown site ═══════════════════════════════════════════════════════════════════════════
Reading from: '/Users/mattcrump/Github/vertical'
Writing to:   '/Users/mattcrump/Github/vertical/docs/dev'
── Initialising site ───────────────────────────────────────────────────────────────────────────────
Writing 'sitemap.xml'
── Building home ───────────────────────────────────────────────────────────────────────────────────
Reading 'LICENSE.md'
Writing 'index.html'
── Building function reference ─────────────────────────────────────────────────────────────────────
Reading 'man/build_vertical.Rd'
Reading 'man/init_jspsych.Rd'
Reading 'man/init_jspsychr.Rd'
Reading 'man/init_papaja.Rd'
Reading 'man/init_poster.Rd'
Reading 'man/init_slides.Rd'
Reading 'man/init_som.Rd'
Reading 'man/suggest_yml.Rd'
Reading 'man/vertical_project.Rd'
── Building articles ───────────────────────────────────────────────────────────────────────────────
Writing 'articles/index.html'
Reading 'vignettes/manuscript/manuscript.Rmd'
Error : callr subprocess failed: invalid multibyte string, element 1
Error: callr subprocess failed: callr subprocess failed: invalid multibyte string, element 1
```

The pdf builds, but there are some weird issues with the abstract, author note and figure references. Have you tried this and got it to work?

**Comment by CrumpLab** [comment]
I think there might be some issue with using the papaja template with pkgdown, but I'm not sure what the issue is. An alternative is to put the manuscript in a manuscript folder, knit it by hand and copy the .pdf to docs.

**Comment by mvuorre** [comment]
The vertical website doesn't build even without the manuscript:

```
── Building articles ────────────────────────────────────────────────────────────────────────────────────
Reading 'vignettes/vertical.Rmd'
Error : callr subprocess failed: pandoc document conversion failed with error 83
 
Error: <callr_status_error: callr subprocess failed: callr subprocess failed: pandoc document conversion failed with error 83>
-->
<callr_remote_error: callr subprocess failed: pandoc document conversion failed with error 83>
 in process 48287 
-->
<callr_remote_error: pandoc document conversion failed with error 83>
 in process 48306 

See `.Last.error.trace` for a stack trace.
```

If you remove references from that file's YML it works.

**Comment by CrumpLab** [comment]
That's weird, `vertical.Rmd` seems to build fine on my end.

**Comment by mvuorre** [comment]
What does `system("pandoc -v")` give you?

```
> system("pandoc -v")
pandoc 2.9.1.1
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3
Default user data directory: /Users/matti/.local/share/pandoc or /Users/matti/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by CrumpLab** [comment]
I'm on OSX mojave 10.14.6

```
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
Default user data directory: /Users/mattcrump/.local/share/pandoc or /Users/mattcrump/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

Looks like I should update pandoc?

**Comment by mvuorre** [comment]
It's not required but probably a good idea. The problem on my end was that I didn't have pandoc-citeproc! (?)

Fix:
```
brew install pandoc-citeproc
```

I will now see why the manuscript isn't compiling.

**Comment by CrumpLab** [comment]
Interesting...well I just updated pandoc. And, vertical compiles with the bibliography in vertical.Rmd.   Fingers crossed about the manuscript. I'm wondering if it has something to do with:

```
This format must accept `template`, `theme`, and `self_contained` in order to work with pkgdown.
```

from pkgdown

**Comment by mvuorre** [comment]
Strange. You can include pdf documents which don't have those arguments. Also, the manuscript does compile just fine, but the pkgdown build process crashes with an error anyway. There is something odd in the papaja author note field however, so I suspect papaja::apa6_pdf is the culprit.

**Comment by CrumpLab** [comment]
I looked into this some more and still can't find a solution. I think pkgdown makes some assumption about rendering that don't jive with papaja. 

My suggestion is we put the manuscript into a `/manuscript` folder, use `vertical::build_vertical()` to build the site, and link to the .pdf in the yml. This seems to work for me with no issues.

**Comment by CrumpLab** [comment]
I updated dev on vertical with the above suggestion. Also, `vertical::build_vertical()` built .Rmds in the `inst` folder, so I added that to the list of folders to ignore in that function.

What do you think about this route? If you're OK with this I'll put the final version of the manuscript there once we have it.

**Comment by mvuorre** [comment]
Yes, that sounds good to me. I also could not find a solution.

**Comment by CrumpLab** [comment]
Alright, will do. I wasn't sure if you'd finished your edits or not, so let me know when I should move it over.

**Comment by mvuorre** [comment]
Thanks! It's up to date so can be moved whenever.

**Comment by CrumpLab** [comment]
Done and done. Vertical master is now updated with this version of the manuscript. Also dev is equal with master on vertical

**Comment by mvuorre** [comment]
Great, thanks! I will delete the rparp repo now.
